package:
  name: flashflood
  version: 0.13.1

source:
  git_rev: 0.13.1
  git_url: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - chorus
    - tornado
    - xlsxwriter

test:
  imports:
    - flashflood

about:
  home: https://github.com/mojaie/flashflood
  license: MIT
  license_file: LICENSE
