package:
  name: flashflood
  version: 0.10.0

source:
  git_rev: v0.10.0
  git_url: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - chorus
    - tornado
    - xlsxwriter
    - pandas
    - python-louvain

test:
  imports:
    - flashflood

about:
  home: https://github.com/mojaie/chorus
  license: MIT
  license_file: LICENSE
